// Auto-generated from CSV. 70 items.
window.SALE_ITEMS = [
  {
    "id": "air-matress-full-size",
    "name": "air matress - full size",
    "category": "bedding",
    "status": "available",
    "originalPrice": 72.24,
    "discount": "50%",
    "finalPrice": 36.12,
    "monthsInUse": 7.2,
    "buyingDate": "October 18, 2025",
    "originalLink": "https://a.co/d/0ej6j13B",
    "image": "images/air matress - full size.png",
    "condition": "second hand"
  },
  {
    "id": "bed-pillows-2x",
    "name": "bed pillows 2x",
    "category": "bedding",
    "status": "available",
    "originalPrice": 28.99,
    "discount": "50%",
    "finalPrice": 14.5,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://a.co/d/09Gae4Wc",
    "image": "images/bed pillows 2x.png",
    "condition": "second hand"
  },
  {
    "id": "comforter-set-queen-size-7-pieces",
    "name": "comforter set - queen size - 7 pieces",
    "category": "bedding",
    "status": "available",
    "originalPrice": 38.99,
    "discount": "70%",
    "finalPrice": 11.7,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0CN34R5W3?ref_=ppx_hzod_title_dt_b_fed_asin_title_1_0",
    "image": "images/comforter set - queen size - 7 pieces.png",
    "condition": "second hand"
  },
  {
    "id": "mattress-queen-size",
    "name": "mattress - queen size",
    "category": "bedding",
    "status": "available",
    "originalPrice": 191.24,
    "discount": "50%",
    "finalPrice": 95.62,
    "monthsInUse": 8.9,
    "buyingDate": "August 27, 2025",
    "originalLink": null,
    "image": "images/mattress - queen size.png",
    "condition": "second hand"
  },
  {
    "id": "sheet-set-queen-size-4-pieces-offwhite",
    "name": "sheet set - queen size - 4 pieces - offwhite",
    "category": "bedding",
    "status": "available",
    "originalPrice": 29.99,
    "discount": "70%",
    "finalPrice": 9,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0CT9R7WN5?ref_=ppx_hzod_title_dt_b_fed_asin_title_1_1",
    "image": "images/sheet set - queen size - 4 pieces - offwhite.png",
    "condition": "second hand"
  },
  {
    "id": "sheet-set-queen-size-4-pieces-white",
    "name": "sheet set - queen size - 4 pieces - white",
    "category": "bedding",
    "status": "available",
    "originalPrice": 29.99,
    "discount": "70%",
    "finalPrice": 9,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0CT9R7WN5?ref_=ppx_hzod_title_dt_b_fed_asin_title_1_1",
    "image": "images/sheet set - queen size - 4 pieces - white.png",
    "condition": "second hand"
  },
  {
    "id": "bucket",
    "name": "bucket",
    "category": "cleaning",
    "status": "available",
    "originalPrice": 15.88,
    "discount": "50%",
    "finalPrice": 7.94,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0D2HWD7YN?ref_=ppx_hzod_title_dt_b_fed_asin_title_1_0",
    "image": "images/bucket.png",
    "condition": "second hand"
  },
  {
    "id": "mop",
    "name": "mop",
    "category": "cleaning",
    "status": "available",
    "originalPrice": 15,
    "discount": "50%",
    "finalPrice": 7.5,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": null,
    "image": "images/mop.png",
    "condition": "second hand"
  },
  {
    "id": "power-mop-pads",
    "name": "power mop + pads",
    "category": "cleaning",
    "status": "available",
    "originalPrice": 29.94,
    "discount": "20%",
    "finalPrice": 23.95,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0C1DWC251?ref_=ppx_hzod_title_dt_b_fed_asin_title_0_0",
    "image": "images/power mop + pads.png",
    "condition": "second hand"
  },
  {
    "id": "artificial-bambu",
    "name": "artificial bambu",
    "category": "decor",
    "status": "available",
    "originalPrice": 89.99,
    "discount": "50%",
    "finalPrice": 45,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.ikea.com/us/en/p/fejka-artificial-potted-plant-indoor-outdoor-bamboo-40568892/",
    "image": "images/artificial bambu.jpg",
    "condition": "second hand"
  },
  {
    "id": "black-floor-lamp",
    "name": "black floor lamp",
    "category": "decor",
    "status": "available",
    "originalPrice": 14,
    "discount": "50%",
    "finalPrice": 7,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": null,
    "image": "images/black floor lamp.jpg",
    "condition": "second hand"
  },
  {
    "id": "entryway-rug",
    "name": "entryway rug",
    "category": "decor",
    "status": "available",
    "originalPrice": 16.4,
    "discount": "50%",
    "finalPrice": 8.2,
    "monthsInUse": 3.7,
    "buyingDate": "January 30, 2026",
    "originalLink": "https://a.co/d/0cl6qUhI",
    "image": "images/entryway rug.png",
    "condition": "second hand"
  },
  {
    "id": "gray-floor-lamp",
    "name": "gray floor lamp",
    "category": "decor",
    "status": "available",
    "originalPrice": 14,
    "discount": "50%",
    "finalPrice": 7,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.target.com/p/torchiere-floor-lamp-room-essentials/-/A-87922467?preselect=87291871#lnk=sametab",
    "image": "images/gray floor lamp.png",
    "condition": "second hand"
  },
  {
    "id": "paiting",
    "name": "paiting",
    "category": "decor",
    "status": "available",
    "originalPrice": 12,
    "discount": "50%",
    "finalPrice": 6,
    "monthsInUse": 9,
    "buyingDate": "August 25, 2025",
    "originalLink": null,
    "image": "images/paiting.png",
    "condition": "second hand"
  },
  {
    "id": "rug-8-x10",
    "name": "rug 8’x10’",
    "category": "decor",
    "status": "available",
    "originalPrice": 75.88,
    "discount": "50%",
    "finalPrice": 37.94,
    "monthsInUse": 1.9,
    "buyingDate": "March 27, 2026",
    "originalLink": "https://a.co/d/0cAkhJsm",
    "image": "images/rug 8'x10'.png",
    "condition": "second hand"
  },
  {
    "id": "table-lamp",
    "name": "table lamp",
    "category": "decor",
    "status": "available",
    "originalPrice": 12,
    "discount": "50%",
    "finalPrice": 6,
    "monthsInUse": 9,
    "buyingDate": "August 24, 2025",
    "originalLink": null,
    "image": "images/table lamp.png",
    "condition": "second hand"
  },
  {
    "id": "table-lamp-with-outlet",
    "name": "table lamp with outlet",
    "category": "decor",
    "status": "available",
    "originalPrice": 12,
    "discount": "50%",
    "finalPrice": 6,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/table lamp with outlet.png",
    "condition": "second hand"
  },
  {
    "id": "throw-pillow-4x",
    "name": "throw pillow 4x",
    "category": "decor",
    "status": "available",
    "originalPrice": 26.89,
    "discount": "50%",
    "finalPrice": 13.45,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B07TJYBLMG?ref=ppx_yo2ov_dt_b_fed_asin_title",
    "image": "images/throw pillow 4x.png",
    "condition": "second hand"
  },
  {
    "id": "throw-pillow-covers-4x",
    "name": "throw pillow covers 4x",
    "category": "decor",
    "status": "available",
    "originalPrice": 27.99,
    "discount": "50%",
    "finalPrice": 14,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": "https://www.amazon.com/dp/B0F1F9L2YR?ref_=ppx_hzod_title_dt_b_fed_asin_title_0_0",
    "image": "images/throw pillow covers 4x.png",
    "condition": "second hand"
  },
  {
    "id": "microwave",
    "name": "microwave",
    "category": "electronics",
    "status": "available",
    "originalPrice": 89.99,
    "discount": "70%",
    "finalPrice": 27,
    "monthsInUse": 9,
    "buyingDate": "August 24, 2025",
    "originalLink": null,
    "image": "images/microwave.png",
    "condition": "second hand"
  },
  {
    "id": "outlet-extender-10-ft",
    "name": "outlet extender - 10 FT",
    "category": "electronics",
    "status": "available",
    "originalPrice": 12.99,
    "discount": "50%",
    "finalPrice": 6.5,
    "monthsInUse": 6,
    "buyingDate": "November 23, 2025",
    "originalLink": "https://a.co/d/0cWexYQx",
    "image": "images/outlet extender - 10 FT.png",
    "condition": "second hand"
  },
  {
    "id": "outlet-extender-5ft",
    "name": "outlet extender - 5FT",
    "category": "electronics",
    "status": "available",
    "originalPrice": 8.99,
    "discount": "50%",
    "finalPrice": 4.5,
    "monthsInUse": 8,
    "buyingDate": "September 24, 2025",
    "originalLink": "https://a.co/d/09bkiCag",
    "image": "images/outlet extender - 5FT.png",
    "condition": "second hand"
  },
  {
    "id": "outlet-extender-5ft-2",
    "name": "outlet extender - 5FT",
    "category": "electronics",
    "status": "available",
    "originalPrice": 8.99,
    "discount": "50%",
    "finalPrice": 4.5,
    "monthsInUse": 8.2,
    "buyingDate": "September 18, 2025",
    "originalLink": "https://a.co/d/09bkiCag",
    "image": "images/outlet extender - 5FT.png",
    "condition": "second hand"
  },
  {
    "id": "robot-vacuum",
    "name": "robot vacuum (barely used)",
    "category": "electronics",
    "status": "available",
    "originalPrice": 114.74,
    "discount": "20%",
    "finalPrice": 91.79,
    "monthsInUse": 8.8,
    "buyingDate": "August 30, 2025",
    "originalLink": "https://a.co/d/0aLmET1V",
    "image": "images/robot vacuum.png",
    "condition": "second hand"
  },
  {
    "id": "bedframe",
    "name": "bedframe",
    "category": "furniture",
    "status": "available",
    "originalPrice": 120,
    "discount": "80%",
    "finalPrice": 24,
    "monthsInUse": 9,
    "buyingDate": "August 24, 2025",
    "originalLink": null,
    "image": "images/bedframe.png",
    "condition": "second hand"
  },
  {
    "id": "chair-2x",
    "name": "chair 2x",
    "category": "furniture",
    "status": "available",
    "originalPrice": 70,
    "discount": "70%",
    "finalPrice": 21,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.ikea.com/us/en/p/stefan-chair-brown-black-00211088/",
    "image": "images/chair 2x.jpg",
    "condition": "second hand"
  },
  {
    "id": "couch",
    "name": "couch",
    "category": "furniture",
    "status": "available",
    "originalPrice": 269,
    "discount": "70%",
    "finalPrice": 80.7,
    "monthsInUse": 9,
    "buyingDate": "August 26, 2025",
    "originalLink": "https://www.ikea.com/us/en/p/klippan-loveseat-vissle-gray-s09010617/",
    "image": "images/couch.png",
    "condition": "second hand"
  },
  {
    "id": "desk",
    "name": "desk",
    "category": "furniture",
    "status": "available",
    "originalPrice": 99.99,
    "discount": "50%",
    "finalPrice": 50,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.ikea.com/us/en/p/micke-desk-black-brown-10244743/",
    "image": "images/desk.png",
    "condition": "second hand"
  },
  {
    "id": "dinner-table",
    "name": "dinner table",
    "category": "furniture",
    "status": "available",
    "originalPrice": 331.66,
    "discount": "70%",
    "finalPrice": 99.5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.homedepot.com/p/Linon-Home-Decor-Angie-Teal-Blue-and-Dark-Gray-Wood-59-in-4-Leg-Dining-Table-Seats-6-THD4572/326109142",
    "image": "images/dinner table.png",
    "condition": "second hand"
  },
  {
    "id": "dresser",
    "name": "dresser",
    "category": "furniture",
    "status": "available",
    "originalPrice": 136.21,
    "discount": "50%",
    "finalPrice": 68.11,
    "monthsInUse": 8.7,
    "buyingDate": "September 4, 2025",
    "originalLink": "https://a.co/d/0cmSpwPT",
    "image": "images/dresser.png",
    "condition": "second hand"
  },
  {
    "id": "flexispot-desk",
    "name": "flexispot desk",
    "category": "furniture",
    "status": "available",
    "originalPrice": 639.99,
    "discount": "70%",
    "finalPrice": 192,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.flexispot.com/flexispot-pro-standing-desk-e7",
    "image": "images/flexispot desk.png",
    "condition": "second hand"
  },
  {
    "id": "foldable-shelf",
    "name": "foldable shelf",
    "category": "furniture",
    "status": "available",
    "originalPrice": 67.94,
    "discount": "50%",
    "finalPrice": 33.97,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.homedepot.com/p/WINSOME-WOOD-Terry-4-Tier-Foldable-Shelf-Narrow-Black-20852/318372372",
    "image": "images/foldable shelf.jpg",
    "condition": "second hand"
  },
  {
    "id": "leather-armchair",
    "name": "leather armchair",
    "category": "furniture",
    "status": "available",
    "originalPrice": 105,
    "discount": "50%",
    "finalPrice": 52.5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.homedepot.com/p/Glamour-Home-Adaya-Cappuccino-Brown-Faux-Leather-Arm-Chair-with-Beech-Legs-Set-of-2-GHDC-1191/312092256",
    "image": "images/leather armchair.png",
    "condition": "second hand"
  },
  {
    "id": "office-desk-chair",
    "name": "office desk chair",
    "category": "furniture",
    "status": "available",
    "originalPrice": 39.86,
    "discount": "70%",
    "finalPrice": 11.96,
    "monthsInUse": 6,
    "buyingDate": "November 23, 2025",
    "originalLink": "https://a.co/d/04iDZkaV",
    "image": "images/office desk chair.jpg",
    "condition": "second hand"
  },
  {
    "id": "office-desk-chair-2",
    "name": "office desk chair",
    "category": "furniture",
    "status": "available",
    "originalPrice": 40,
    "discount": "70%",
    "finalPrice": 12,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": null,
    "image": "images/office desk chair.png",
    "condition": "second hand"
  },
  {
    "id": "rustic-coffee-table",
    "name": "rustic coffee table",
    "category": "furniture",
    "status": "available",
    "originalPrice": 150,
    "discount": "50%",
    "finalPrice": 75,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/rustic coffee table.png",
    "condition": "second hand"
  },
  {
    "id": "shoe-cabinet-bench",
    "name": "shoe cabinet + bench",
    "category": "furniture",
    "status": "available",
    "originalPrice": 152.99,
    "discount": "50%",
    "finalPrice": 76.5,
    "monthsInUse": 8.7,
    "buyingDate": "September 4, 2025",
    "originalLink": "https://a.co/d/07ohBY1B",
    "image": "images/shoe cabinet + bench.png",
    "condition": "second hand"
  },
  {
    "id": "side-table-morsman",
    "name": "side table - morsman",
    "category": "furniture",
    "status": "available",
    "originalPrice": 99.99,
    "discount": "70%",
    "finalPrice": 30,
    "monthsInUse": 9,
    "buyingDate": "August 24, 2025",
    "originalLink": "https://www.etsy.com/pt/listing/1183845960/mersman-vintage-mid-century-modern-end?show_sold_out_detail=1&ref=nla_listing_details",
    "image": "images/side table - morsman.png",
    "condition": "second hand"
  },
  {
    "id": "side-table-round",
    "name": "side table round",
    "category": "furniture",
    "status": "available",
    "originalPrice": 46.49,
    "discount": "50%",
    "finalPrice": 23.25,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.target.com/p/the-urban-port-15-34-modern-side-end-table-metal-round-tray-top-foldable-legs-black/-/A-93171292",
    "image": "images/side table round.jpg",
    "condition": "second hand"
  },
  {
    "id": "side-table-with-drawers",
    "name": "side table with drawers",
    "category": "furniture",
    "status": "available",
    "originalPrice": 40,
    "discount": "50%",
    "finalPrice": 20,
    "monthsInUse": 8.9,
    "buyingDate": "August 28, 2025",
    "originalLink": null,
    "image": "images/side table with drawers.png",
    "condition": "second hand"
  },
  {
    "id": "blender",
    "name": "blender",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 20,
    "discount": "70%",
    "finalPrice": 6,
    "monthsInUse": 7.4,
    "buyingDate": "October 13, 2025",
    "originalLink": "https://www.target.com/p/hamilton-beach-one-speed-single-serve-blender-black/-/A-11893664",
    "image": "images/blender.jpg",
    "condition": "second hand"
  },
  {
    "id": "cake-pan-small",
    "name": "cake pan small",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 9,
    "discount": "50%",
    "finalPrice": 4.5,
    "monthsInUse": 8.5,
    "buyingDate": "September 8, 2025",
    "originalLink": null,
    "image": "images/cake pan small.jpg",
    "condition": "second hand"
  },
  {
    "id": "champagne-flute-4x",
    "name": "champagne flute 4x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 12,
    "discount": "60%",
    "finalPrice": 4.8,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/champagne flute 4x.jpg",
    "condition": "second hand"
  },
  {
    "id": "cookie-sheet-large",
    "name": "cookie sheet large",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 9,
    "discount": "50%",
    "finalPrice": 4.5,
    "monthsInUse": 8.5,
    "buyingDate": "September 8, 2025",
    "originalLink": "https://www.target.com/p/goodcook-11-34-x17-34-nonstick-steel-cookie-sheet-gray/-/A-88232825#lnk=sametab",
    "image": "images/cookie sheet large.png",
    "condition": "second hand"
  },
  {
    "id": "crock-pot",
    "name": "crock pot",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 89.87,
    "discount": "60%",
    "finalPrice": 35.95,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.walmart.com/ip/Crock-Pot-7-Quart-Smart-Pot-Slow-Cooker-Brushed-Stainless-Steel/54947078",
    "image": "images/crock pot.jpg",
    "condition": "second hand"
  },
  {
    "id": "dinner-plate-3x",
    "name": "dinner plate 3x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 30,
    "discount": "50%",
    "finalPrice": 15,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/dinner plate 3x.jpg",
    "condition": "second hand"
  },
  {
    "id": "flatware",
    "name": "flatware",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 15,
    "discount": "50%",
    "finalPrice": 7.5,
    "monthsInUse": 8.8,
    "buyingDate": "September 1, 2025",
    "originalLink": "https://www.target.com/p/20pc-teagan-flatware-silver-room-essentials-8482/-/A-14901073#lnk=sametab",
    "image": "images/flatware.png",
    "condition": "second hand"
  },
  {
    "id": "glass-2x",
    "name": "glass 2x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 16,
    "discount": "50%",
    "finalPrice": 8,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/glass 2x.jpg",
    "condition": "second hand"
  },
  {
    "id": "ikea-plates-5x",
    "name": "ikea plates 5x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 25,
    "discount": "50%",
    "finalPrice": 12.5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.ikea.com/us/en/p/faergklar-18-piece-dinnerware-set-matte-dark-gray-20564710/",
    "image": "images/ikea plates 5x.jpg",
    "condition": "second hand"
  },
  {
    "id": "manual-can-opener",
    "name": "manual can opener",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 12.99,
    "discount": "50%",
    "finalPrice": 6.5,
    "monthsInUse": 7.2,
    "buyingDate": "October 18, 2025",
    "originalLink": "https://www.target.com/p/movssou-manual-can-opener-stainless-steel-safe-smooth-edge/-/A-93276577",
    "image": "images/manual can opener.png",
    "condition": "second hand"
  },
  {
    "id": "mugs-4x",
    "name": "mugs (4x)",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 12.74,
    "discount": "50%",
    "finalPrice": 6.37,
    "monthsInUse": 8.3,
    "buyingDate": "September 15, 2025",
    "originalLink": "https://a.co/d/07d08yoG",
    "image": "images/mugs (4x).png",
    "condition": "second hand"
  },
  {
    "id": "pie-dish",
    "name": "pie dish",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 20,
    "discount": "50%",
    "finalPrice": 10,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": null,
    "image": "images/pie dish.jpg",
    "condition": "second hand"
  },
  {
    "id": "plastic-bowl-2x",
    "name": "plastic bowl 2x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 10,
    "discount": "50%",
    "finalPrice": 5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/plastic bowl 2x.jpg",
    "condition": "second hand"
  },
  {
    "id": "plastic-plates-5x",
    "name": "plastic plates 5x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 10,
    "discount": "50%",
    "finalPrice": 5,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": null,
    "image": "images/plastic plates 5x.jpg",
    "condition": "second hand"
  },
  {
    "id": "popcorn-popper",
    "name": "popcorn popper",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 15,
    "discount": "50%",
    "finalPrice": 7.5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/popcorn popper.jpg",
    "condition": "second hand"
  },
  {
    "id": "serving-bowl",
    "name": "serving bowl",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 30,
    "discount": "30%",
    "finalPrice": 21,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": null,
    "image": "images/serving bowl.jpg",
    "condition": "second hand"
  },
  {
    "id": "shot-glass",
    "name": "shot glass",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 20,
    "discount": "60%",
    "finalPrice": 8,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": null,
    "image": "images/shot glass.jpg",
    "condition": "second hand"
  },
  {
    "id": "small-shot-glass",
    "name": "small shot glass",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 8,
    "discount": "50%",
    "finalPrice": 4,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/small shot glass.jpg",
    "condition": "second hand"
  },
  {
    "id": "stub-glass-low-3x",
    "name": "stub glass - low 3x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 20,
    "discount": "50%",
    "finalPrice": 10,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/stub glass - low 3x.jpg",
    "condition": "second hand"
  },
  {
    "id": "stub-glass-tall-5x",
    "name": "stub glass - tall 5x",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 40,
    "discount": "50%",
    "finalPrice": 20,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/stub glass - tall 5x.jpg",
    "condition": "second hand"
  },
  {
    "id": "utensil-set-with-holder",
    "name": "utensil set with holder",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 10,
    "discount": "50%",
    "finalPrice": 5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/utensil set with holder.png",
    "condition": "second hand"
  },
  {
    "id": "water-filter",
    "name": "water filter",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 5,
    "discount": "50%",
    "finalPrice": 2.5,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": null,
    "image": "images/water filter.png",
    "condition": "second hand"
  },
  {
    "id": "water-filter-pitcher",
    "name": "water filter pitcher",
    "category": "kitchen",
    "status": "available",
    "originalPrice": 16,
    "discount": "50%",
    "finalPrice": 8,
    "monthsInUse": 8.8,
    "buyingDate": "August 31, 2025",
    "originalLink": "https://www.cvs.com/shop/brita-small-6-cup-denali-water-filter-pitcher-with-1-brita-standard-filter-white-prodid-822759",
    "image": "images/water filter pitcher.png",
    "condition": "second hand"
  },
  {
    "id": "3-drawer-stacking",
    "name": "3-drawer stacking",
    "category": "organizers",
    "status": "available",
    "originalPrice": 20.99,
    "discount": "50%",
    "finalPrice": 10.5,
    "monthsInUse": 7.1,
    "buyingDate": "October 21, 2025",
    "originalLink": "https://www.target.com/p/iris-medium-3-drawer-stacking-desktop-organizer--1-pack--plastic-drawer-storage-container-for-stationery-art-craft-supplies--white/-/A-87079304",
    "image": "images/3-drawer stacking.png",
    "condition": "second hand"
  },
  {
    "id": "desk-tool-organizer",
    "name": "desk tool organizer",
    "category": "organizers",
    "status": "available",
    "originalPrice": 14,
    "discount": "50%",
    "finalPrice": 7,
    "monthsInUse": 7.3,
    "buyingDate": "October 15, 2025",
    "originalLink": "https://www.target.com/p/canvas-desk-tool-holder-organizer-black---brightroom--8482---desktop---38--office-organizers--polyester-canvas--12-25--34--width/-/A-86941073",
    "image": "images/desk tool organizer.png",
    "condition": "second hand"
  },
  {
    "id": "drawer-organizer",
    "name": "drawer organizer",
    "category": "organizers",
    "status": "available",
    "originalPrice": 12,
    "discount": "50%",
    "finalPrice": 6,
    "monthsInUse": null,
    "buyingDate": null,
    "originalLink": "https://www.amazon.com/Madesmart-Classic-4-Compartment-Organizer-Multipurpose/dp/B00EE05GG0?th=1",
    "image": "images/drawer organizer.jpg",
    "condition": "second hand"
  },
  {
    "id": "makeup-organizer",
    "name": "makeup organizer",
    "category": "organizers",
    "status": "available",
    "originalPrice": 15,
    "discount": "50%",
    "finalPrice": 7.5,
    "monthsInUse": 7.3,
    "buyingDate": "October 16, 2025",
    "originalLink": "https://www.target.com/p/makeup-turntable-beauty-vanity-organizer-small---brightroom--8482---clear-plastic-makeup-storage-with-5-compartments--7--34-x7--34-x5-88--34-/-/A-75663616",
    "image": "images/makeup organizer.png",
    "condition": "second hand"
  },
  {
    "id": "organizer-set",
    "name": "organizer set",
    "category": "organizers",
    "status": "available",
    "originalPrice": 12,
    "discount": "50%",
    "finalPrice": 6,
    "monthsInUse": 8.5,
    "buyingDate": "September 8, 2025",
    "originalLink": "https://www.target.com/p/6pc-plastic-drawer-organizer-clear-brightroom-8482/-/A-83901180#lnk=sametab",
    "image": "images/organizer set.png",
    "condition": "second hand"
  },
  {
    "id": "storage-bin",
    "name": "storage bin",
    "category": "organizers",
    "status": "available",
    "originalPrice": 8,
    "discount": "20%",
    "finalPrice": 6.4,
    "monthsInUse": 7.2,
    "buyingDate": "October 17, 2025",
    "originalLink": "https://www.target.com/p/32qt-clear-storage-bin-with-latches---brightroom--8482-/-/A-93286401",
    "image": "images/storage bin.png",
    "condition": "second hand"
  },
  {
    "id": "yoga-mat",
    "name": "yoga mat",
    "category": "others",
    "status": "available",
    "originalPrice": 24.99,
    "discount": "50%",
    "finalPrice": 12.5,
    "monthsInUse": 9,
    "buyingDate": "August 25, 2025",
    "originalLink": "https://www.amazon.com/dp/B091FXKQZ6?ref=ppx_yo2ov_dt_b_fed_asin_title",
    "image": "images/yoga mat.png",
    "condition": "second hand"
  }
];
